apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels: {}
    name: httpbin-kargo-stages
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: httpbin
    source:
        path: deploy/projects/httpbin/components/kargo-stages
        repoURL: https://github.com/holos-run/kargo-demo.git
        targetRevision: main
