apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        kargo.akuity.io/authorized-stage: httpbin:prod-us-east
    labels: {}
    name: httpbin-prod-us-east-httpbin
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: httpbin
    source:
        path: ./
        repoURL: https://github.com/holos-run/kargo-demo.git
        targetRevision: project/httpbin/component/prod-us-east-httpbin
