apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    argocd.argoproj.io/instance: argocd-kargo-secrets
  name: admin-credentials
  namespace: kargo
spec:
  dataFrom:
  - rewrite:
    - transform:
        template: password
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: admin-password-generator
  - rewrite:
    - transform:
        template: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: admin-signing-key-generator
  refreshInterval: 24h
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        ADMIN_ACCOUNT_PASSWORD_HASH: '{{ .password | bcrypt }}'
      engineVersion: v2
      mergePolicy: Merge
      type: Opaque
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  labels:
    argocd.argoproj.io/instance: argocd-kargo-secrets
  name: admin-password-generator
  namespace: kargo
spec:
  allowRepeat: true
  digits: 4
  length: 32
  noUpper: false
  symbols: 4
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  labels:
    argocd.argoproj.io/instance: argocd-kargo-secrets
  name: admin-signing-key-generator
  namespace: kargo
spec:
  allowRepeat: true
  digits: 4
  length: 32
  noUpper: false
  symbols: 4
