apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        kargo.akuity.io/authorized-stage: podinfo:prod-us-central-podinfo
    labels: {}
    name: podinfo-prod-us-central-podinfo
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: podinfo
    source:
        path: ./
        repoURL: https://github.com/holos-run/kargo-demo.git
        targetRevision: project/podinfo/component/prod-us-central-podinfo
