apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        kargo.akuity.io/authorized-stage: podinfo:test
    labels: {}
    name: podinfo-test-podinfo
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: podinfo
    source:
        path: ./
        repoURL: https://github.com/holos-run/kargo-demo.git
        targetRevision: project/podinfo/component/test-podinfo
