apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels: {}
    name: argocd-argocd
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: argocd
    source:
        path: deploy/components/argocd
        repoURL: https://github.com/holos-run/kargo-demo.git
        targetRevision: main
