apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels: {}
    name: security-cert-manager-kargo
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: security
    source:
        path: deploy/components/cert-manager-kargo
        repoURL: https://github.com/jeffmccune/kargo-demo.git
        targetRevision: main
