apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels: {}
    name: network-istio-promoter
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: network
    source:
        path: deploy/components/istio-promoter
        repoURL: https://github.com/holos-run/kargo-demo.git
        targetRevision: main
